
<header>
        <div class="container">
            <div class="logo">
                <a href="index.html">
                    <img src="../../images/logo site MyHealth.jpg"  alt="Logo da Plataforma de Saúde">
                </a>
            </div>
            <nav>
                <ul>
                    <li><a href="index.php">Início</a></li>
                    <li><a href="servicos.php">Serviços</a></li>
                    <li><a href="sobre.php">Sobre Nós</a></li>
                    <li><a href="contato.php">Contato</a></li>
                </ul>
            </nav>
            <div class="login">
                <a href="login.php" class="btn-login">Login</a>
                <a href="cadastrar.php" class="btn-login">Cadastre-se</a>
            </div>
        </div>
    </header>